### ISSUE TITLE
integer minus signed wrongly encoded

### ISSUE THREAD

**Issue by bobifle** [Arokha/EP2-Data#4]
A lot of minus signs are encoded using the utf8 character \u2013. This is a weird choice, probably a mistake/pdf extraction issue.

minus signed preceeding integers should be encoded with the ascii minus code to allow proper integer conversion.

For instance in gears_drugs.json, the addiction is noted as '\u201310' , which may display almot correctly, but won't be properly converted into integer by tools using the json data.

**Comment by bobifle** [comment]
I may have a patch for this ...

**Comment by bobifle** [comment]
the sanityze.py script from PR #3 should fix this.

**Comment by Arokha** [comment]
Fixed in #6
