### ISSUE TITLE
Invalid UTF8 BOM in some files

### ISSUE THREAD

**Issue by bobifle** [Arokha/EP2-Data#5]
Some of the json files are invalid, they contain the UTF8 BOM while the standard forbids it. See https://tools.ietf.org/html/rfc7159#section-8.1

Some json decoders will report the json as invalid.

Note that some files do not contain the BOM,

**Comment by bobifle** [comment]
the sanitize.py script from PR #3 should fix this

**Comment by Arokha** [comment]
Fixed in #6
