### ISSUE TITLE
sleights and traits are objects without a name

### ISSUE THREAD

**Issue by bobifle** [Arokha/EP2-Data#7]
The following files are list of json objects without a "name"

sleights.json
traits.json
chargen.json
gear_text.json

For consistency sake I'd suggest:
change the "sleights" key into "name"
change the "traits" key into "name"

This way we'll have a common structure a way to meaningfully identifies objects in their list.

For gear_text:
It's a list of additional info about gear right ? so it could be a list, and possible a name, i.e. use the same structure as other objects.
{"Armor": {"text": "...."}} would be changed into
[{"name": "Armor", text: "..."}]

for char_gen you could also rename "step_name" into "name".

What's your thoughts on that ?

PS : FYI I'm using the data in an app and having a common way to id objects would be very usefull, right now, I have to customize the identifier for traits and sleights (not big of a deal)

PPS : I could PR a proposal if you interested, the modifications should be trivial with a dozen of python code lines.

**Comment by Arokha** [comment]
Can PR it if you'd like! I'm probably working on a similar app... a character sheet thingy.

**Comment by bobifle** [comment]
Nope I'm building a eclipse 2 framework for the free open source vtt maptool.

So no overlap here 😎

**Comment by Arokha** [comment]
Neat! Throw it on reddit when done? Or somewhere. I'd like to grab it.

**Comment by Leshana** [comment]
As far as gear_text.json goes, I needed to fix that anyway so it would be an array like all the other files.  Something like this:  https://github.com/Arokha/EP2-Data/pull/8/files#diff-dcb15c2c3b5e0e093a560476d7546fea  what you had in mind for gear text?

**Comment by bobifle** [comment]
Yep that would totally fix gear_text.json

**Comment by Arokha** [comment]
Partially resolved in #10

**Comment by Arokha** [comment]
Think this is resolved now
